apiVersion: v1
kind: Service
metadata:
  name: redis-db
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379 # port where the backend is exposed (the app running in the pod)
      port: 6379 # service port
  selector:
    app: myapp
    name: redis-pod