apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: frontend
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"



# apiVersion - version of kubernetes API we are using to create objects
# kind - kind of object we are creating eg Pod, ReplicaSet, Service, Deployment (case sensitive)
# metadata - data about the object
# spec - specification
# to recreate a pod after modifying the pod definition yaml file --> kubectl apply -f pod-defintion.yml